const authTypes = {
  CHECK_AUTHENTICATION: 'TYPE IS AUTH CHECK AUTHENTICATION',
  LOGOUT: 'TYPE AUTH LOGOUT',
  LOGIN: 'TYPE AUTH LOGIN',
  CHANGE_EDIT_MODE: 'TYPE AUTH EDIT DATA INPUT',
  SHOW_LOGOUT_MODAL: 'TYPE AUTH SHOW LOGOUT MODAL',
  SHOW_REGISTER: 'TYPE AUTH SHOW REGISTER MODAL',
  ON_CHANGE: 'TYPE AUTH ON CHANGE',
}
export default authTypes