const calendarTypes = {
  GET_DATA: 'CALENDAR TYPE GET DATA',
  RESET_FILTER: 'CALENDAR ON RESET FILTER',
  DATAITEM_CHANGE: 'CALENDAR ON DATAITEM CHANGE',
  DATASTATE_CHANGE: 'CALENDAR ON DATASTATE CHANGE',
  GENERAL_FILTER_CHANGE: 'CALENDAR ON GENERAL FILTER CHANGE',
  ROLE_FILTER_CHANGE: 'CALENDAR ON ROLE FILTER CHANGE',
  VIEW_MODE: 'CALENDAR VIEW MODE TOGGLE',
  EDIT_DATA: 'CALENDAR EDIT DATA',
  GET_DETAIL: 'CALENDAR TYPE GET DETAIL',
  DISCARD: 'CALENDAR DISCARD',
  REMOVE_DATA: 'CALENDAR REMOVE DATA',
  CHANGE_EDIT_MODE: 'CALENDAR EDIT DATA INPUT',
  GET_FIELD_CALENDAR: 'CALENDAR GET EMPLOYEE',
  CLOSE_AUTOCOMPLETE: 'CALENDAR CLOSE AUTOCOMPLETE',
  GET_IMAGE: 'CALENDAR GET IMAGE'
}
export default calendarTypes