const trainingTypes = {
  GET_DATA: 'TRAINING TYPE GET DATA',
  RESET_FILTER: 'TRAINING ON RESET FILTER',
  DATAITEM_CHANGE: 'TRAINING ON DATAITEM CHANGE',
  DATASTATE_CHANGE: 'TRAINING ON DATASTATE CHANGE',
  GENERAL_FILTER_CHANGE: 'TRAINING ON GENERAL FILTER CHANGE',
  ROLE_FILTER_CHANGE: 'TRAINING ON ROLE FILTER CHANGE',
  VIEW_MODE: 'TRAINING VIEW MODE TOGGLE',
  EDIT_DATA: 'TRAINING EDIT DATA',
  GET_DETAIL: 'TRAINING TYPE GET DETAIL',
  DISCARD: 'TRAINING DISCARD',
  REMOVE_DATA: 'TRAINING REMOVE DATA',
  CHANGE_EDIT_MODE: 'TRAINING EDIT DATA INPUT',
  GET_FIELD_TRAINING: 'TRAINING GET EMPLOYEE',
  CLOSE_AUTOCOMPLETE: 'TRAINING CLOSE AUTOCOMPLETE',
  GET_IMAGE: 'TRAINING GET IMAGE'
}
export default trainingTypes