const transactChatTypes = {
  GET_DATA:'TRANSACT CHAT TYPES GET DATA',
  GET_ROOM_DATA:'TRANSACT CHAT TYPES GET ROOM DATA',
  GET_MESSAGES:'TRANSACT CHAT TYPES GET MESSAGES',
  POST_CHAT:'TRANSACT CHAT POST CHAT',
  MUTE_USER:'TRASNSACT CHAT MUTE USER',
  CLICK_CHAT_ROOM:'TRANSACT CHAT TYPES ON CLICK CHAT ROOM',
  TYPING:'TRANSACT CHAT TYPES ON TYPE MESSAGE',
  TOOGLE_CREATE_ROOM:'TRANSACT CHAT TYPES TOOGLE CREATE ROOM',
  ON_CHANGE_AUTOCOMPLETE:'TRANSACT CHAT TYPES ON CHANGE AUTO COMPLETE',
  GET_PORTAL_USER:'TRANSACT CHAT TYPES GET PORTAL USER',
  ADD_MEMBER:'TRANSACT CHAT TYPES ADD MEMBERS',
  REMOVE_MEMBER:'TRANSACT CHAT TYPES REMOVE MEMBER',
  CHANGE_GROUP_NAME:'TRANSACT CHAT TYPES ON CHANGE GROUP NAME',
  CREATE_ROOM:'TRANSACT CHAT TYPES ON CREATE ROOM',
  SUBSCRIPTION_CREATE_ROOM:'TRANSACT CHAT TYPES ON HANDLE SUBSCRIPTION CREATE ROOM',
  CREATE_ROOM_LOADING:'TRANSACT CHAT TYPES CREATE ROOM LOADING',
  HANDLE_SUBSCRIPTION:'TRANSACT CHAT HANDLE SUBSCRIPTION'
}
export default transactChatTypes